### ISSUE TITLE
Incorrect Sound Being Played During Battles

### ISSUE THREAD

**Issue by SlainteMaith** [mighty-bean/DarkishTower#5]
My wife and I have built this successfully.  I will note that one of the battle sounds (The sound played when your warriors win their turn) is played at the wrong time.  
The sound that happens in its place is not in the original game.
The sound that's supposed to happen occurs instead when you purchase something successfully from the bazaar. (Two "horn" notes)
We were hoping to correct the code on this, but we couldn't find the lines where anything gets played at the Bazaar apart from SoundFile bazaar_snd = { bazaar_sample_count, bazaar_sample_data };
SoundFile bazaar_closed_snd = { bazaar_closed_sample_count, bazaar_closed_sample_data };

**Comment by mighty-bean** [comment]
Probably easier to change the code that requests each sound to play from the active game screen. 
That's all in https://github.com/mighty-bean/DarkishTower/blob/main/src/game_screens.cpp
Look for calls like: gGameState.soundManager.play(<some_sound_name>, true);

The odd thing is that the Warrior win sound (line 1317) and the Bazaar purchase sound (line 1960) are both currently set to play the same sound file: gGameState.soundManager.play(pegasus_snd, true);

I'm afraid that I don't have a unit to test this on right now, but hopefully this information helps.

**Comment by ecodad** [comment]
I'm trying to build this now.  When I try to compile in Arduino IDE 2.2.1 - I get the following error codes complaining about the sound_manager.cpp

`error: 'dacWrite' was not declared in this scope;
error: 'usleep' was not declared in this scope`

Any suggestions on what I need to update for the current IDE environment?

**Comment by MicFre173** [comment]
Line 1317 needs to be enemy_hit_snd instead of pegasus_snd.

**Comment by MicFre173** [comment]
Created a pull request to fix this.
#7
